### ISSUE TITLE
Profile and Name are not updating

### ISSUE THREAD

**Issue by YoCazza** [EntityEvolution/ev-topkill#3]
When players join with a new Discord profile picture or Discord name, it doesn't update in the database. Adding this feature would be awesome!

**Comment by BombayV** [comment]
At the moment, this is not possible. The only thing I could do at the moment is add a command like /updateavatar <player_server_id>

**Comment by YoCazza** [comment]
This feature would be great! Helps allot because now some players dont have a profile picture.

**Comment by BombayV** [comment]
@YoCazza Feel free to try this. https://github.com/EntityEvolution/ev-topkill/tree/dev

You should be able to do `/updateAvatar <targetServerSource>`

**Comment by YoCazza** [comment]
Works Great! Thanks! 😀

Maybe to finetune the feature: check if the player exists in the database. If the player is found, update their profile every time they join. If the player is new and not in the database then 'return'.

Thanks for this fast working update!

**Comment by BombayV** [comment]
The problem with that is that if a lot of people join at the same time, the resource would probably get rate-limited for a little bit. Thank you either way.
